### PR TITLE
gui args: pass the series in addCharm and deploy changes.

### PR DESCRIPTION
**Pull request by frankban**
Also provide resources info in deploy changes.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundlechanges/75/
Test PASSed.

**Comment by fabricematrat** [comment]
:+1:

**Comment by rogpeppe** [comment]
LGTM, thanks

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundlechanges-merge

**Pull request merged**
