### PR TITLE
Add endpoint bindings

### PR DESCRIPTION
**Pull request by dooferlad**
Adds support for a bundle containing endpoint bindings, for example:
```yaml
services:
    django:
        charm: django
        bindings:
            foo: bar
```
This would bind endpoint foo into space bar for service django.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundlechanges/41/
Test PASSed.

**Comment by dimitern** [comment]
Awesome! LGTM and thanks!

**Comment by dooferlad** [comment]
$$merge$$

**Comment by dooferlad** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundlechanges-merge

**Pull request merged**
