### PR TITLE
get-bundle-changes: print all errors when the given bundle is not valid.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundlechanges/50/
Test PASSed.

**Comment by fabricematrat** [comment]
:+1:

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundlechanges-merge

**Pull request merged**
