### PR TITLE
Introduce expose change.

### PR DESCRIPTION
**Pull request by frankban**
It is used to expose services when deploying bundles.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundlechanges/37/
Test PASSed.

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by rogpeppe** [comment]
LGTM thanks

**Comment by frankban** [comment]
Thank you Martin and Roger for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundlechanges-merge

**Pull request merged**
