### PR TITLE
Update deps to use stable version of charm and charmrepo

### PR DESCRIPTION
**Pull request by wallyworld**
Update dependencies:
- use stable versions of charm and charmrepo
- use up-to-date version of other repos to match what juju uses

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/bundlechanges/109/

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/bundlechanges-merge

**Pull request merged**
