### PR TITLE
Use stable charm.v5.

### PR DESCRIPTION
**Pull request by frankban**
For now, this would make it easy to integrate with juju-core.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundlechanges/23/
Test PASSed.

**Comment by mhilton** [comment]
:+1:

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundlechanges-merge

**Pull request merged**
