### PR TITLE
Deterministic

### PR DESCRIPTION
**Pull request by SimonRichardson**
The following ensure that the applications that we loop through are
deterministic, so that when adding application units we skip correctly
with in the loop.

This is fixing LP #1883645

### CODE REVIEW

**Comment by howbazaar** [comment]
Hey @SimonRichardson , we should have made the juju-2.7 branch based off the revision that 2.7 was using rather than tip.

I'll look to update this now. That way you don't need to include the godeps file.

**Comment by howbazaar** [comment]
I see that this branch was created before, and the tip of this is what is currently referenced in juju/2.7 branch, so I guess it's ok.

**Comment by SimonRichardson** [comment]
@howbazaar yeah I spent some time checking that and ensuring it was correct with @achilleasa

**Comment by SimonRichardson** [comment]
$$merge$$

**Pull request merged**
