### PR TITLE
Code reorganization.

### PR DESCRIPTION
**Pull request by frankban**
This branch does not include any new code. It just moves the handlers into their own handlers.go file, and updates the charm dependency. This is in preparation of a refactoring.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundlechanges/27/
Test PASSed.

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by frankban** [comment]
Thanks Martin!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundlechanges-merge

**Pull request merged**
