### PR TITLE
Generate unit changes.

### PR DESCRIPTION
**Pull request by frankban**
Handle unit placement directives, and also generate new
machines and containers accordingly.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundlechanges/15/
Test PASSed.

**Comment by makyo** [comment]
Awesome :+1: QA Okay

**Comment by mhilton** [comment]
:+1:

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundlechanges-merge

**Pull request merged**
