### PR TITLE
Service to application

### PR DESCRIPTION
**Pull request by wallyworld**
Services are renamed to applications. The juju/charm.v6-unstable repo has been updated to parse bundle containing applications, and data structs like BundleData have had their attributes renamed. This PR contains the changes to account for the upstream code changes.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundlechanges/71/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundlechanges/72/
Test PASSed.

**Comment by makyo** [comment]
:+1: QA OK

**Comment by mhilton** [comment]
:+1:

**Comment by makyo** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundlechanges-merge

**Pull request merged**
