### PR TITLE
Add Series attribute to AddCharmParams

### PR DESCRIPTION
**Pull request by wallyworld**
When a charm is added, we support the bundle specifying the series.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundlechanges/46/
Test FAILed.

**Comment by axw** [comment]
LGTM, looks like you need to update the charm package first though.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundlechanges/47/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundlechanges/48/
Test PASSed.

**Comment by wallyworld** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundlechanges-merge

**Pull request merged**
